import React from "react";
import { Header, Button } from "semantic-ui-react";
import MyList from "../components/lists.js";
import TextInput from "../components/TextInputModal.js";

class OKR extends React.Component {
    constructor(props)
    {
        super(props);
        this.state = {
            list: [123,456,789,0],
            key_object: "Change the world!",
            modal_actived: false,
            modal_for: ""
        };
    }
    delete_item({ event, index })
    {
        console.log({ event, index });
        return;
    }
    set_modal_actived()
    {
        this.setState({ modal_actived: !this.state.modal_actived });
    }
    /**
     * Do whatever actions once get response from modal
     * @param {object} payload
     * @param {object} payload.event - DOM event generated by React itself.
     * @param {boolean} payload.bool - Positive or negative response.
     * @param {string} payload.content - What text inputed in modal.
     * @returns void
     * @memberof OKR
     */
    modal_response_method(payload)
    {
        let setted_state = {
            modal_for: ""
        };
        let method_actions = {
            "key_object": {
                prop: "key_object",
                value: payload.content
            },
            "key_result": {
                prop: "list",
                value: [ ...this.state.list ].push( payload.content )
            },
        };
        let current_modal = method_actions[ this.state.modal_for ];
        this.set_modal_actived();
        setted_state[ current_modal.prop ] = current_modal.value;
        this.setState( setted_state );
        return;
    }
    active_modal(modal_for)
    {
        this.setState({ modal_for });
        this.set_modal_actived();
    }
    render()
    {
        return (
        <div id="OKR">
            <Header as="h1">Object</Header>
            <p>{ this.state.key_object }</p>
            <Button size="mini" onClick={ event => this.active_modal("key_object") }>Add key object</Button>
            <Header as="h2">Key result</Header>
            <MyList list={ this.state.list }  />
            <Button size="mini" onClick={ event => this.active_modal("key_result") }>Add key result</Button>
            <TextInput open={ this.state.modal_actived } modal_response_method={ this.modal_response_method.bind(this) }/>
        </div>
        );
    }
};

export default OKR;